url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "FHGR Online Marketing Cards" # the name of your site, e.g. ACME Corp.
description: ""
organization-name: "Fachhochschule Graubünden"
organization-link: "https://www.fhgr.ch"
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
sass:
  sass_dir: "./assets/scss"
  style: "compressed"
