# _config.yml
source: src
destination: .docs
url: "https://sandromatter.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/fhgr-online-marketing-cards" # the subpath of your site, e.g. /blog
title: "FHGR Online Marketing Cards" # the name of your site, e.g. ACME Corp.
description: "Die Onlineausgabe der Online Marketing Cards der FH Graub체nden. Die Lernkarten, welche die Vorz체ge und Nachteile der meistgebrauchten Tools und Plattformen im digitalen Marketing erkl채ren."
organization-name: "Fachhochschule Graub체nden"
organization-link: "https://www.fhgr.ch"
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
sass:
  sass_dir: "assets/scss"
  style: "compressed"
